import type { VehicleType } from './FarmModels';

export const initialVehicles: Record<VehicleType, number> = {
  tracteur: 5,
  remorque: 3,
  moissonneuse: 2,
  charrue: 2,
  fertilisateur: 2,
  semeuse: 2,
  'remorque semi': 1,
  'moissonneuse à raisin': 1,
  'moissonneuse à olive': 1,
  'moissonneuse à pomme de terre': 1,
  'moissonneuse à betterave': 1,
  'moissonneuse à coton': 1,
  'moissonneuse à canne': 1,
  'moissonneuse à arbre': 1,
  'moissonneuse à légumes': 1,
  'moissonneuse à épinard': 1,
  'moissonneuse à pois': 1,
  'moissonneuse à haricots': 1,
  'planteuse à arbre': 1,
  'planteuse à pomme de terre': 1,
  'planteuse à canne': 1,
  'planteuse légumes': 1,
};
